// 모든페이지에 보일 엘리먼트는 이곳에 작성. 예)nav,footer
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="navbar">
        <Link href="/">홈</Link>
        <Link href="/list">List</Link>
        <Link href="/cart">장바구니</Link>
      </div>
      {children}
      </body>
    </html>
  );
}
